
# ID du projet Supabase actuel
project_id = "kbmnsxakgyokifzoiajo"

# Site URL personnalisée pour les redirections d'authentification
site_url = "https://bibliopulse.com"

# URL de redirection précise pour l'authentification
redirect_urls = ["https://bibliopulse.com/auth/callback"]
