
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Configuration du projet Supabase actuel
const SUPABASE_URL = "https://kbmnsxakgyokifzoiajo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtibW5zeGFrZ3lva2lmem9pYWpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2MzMxOTksImV4cCI6MjA1ODIwOTE5OX0.I199rtDVCWA0iFf5hD9dZWH1g7tukQXltFJfg5TTThM";

// Create Supabase client with additional options for better consistency
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      storage: localStorage,
      flowType: 'pkce',
      // Assurer que l'URL absolue complète est utilisée pour les redirections
      redirectTo: 'https://bibliopulse.com/auth/callback',
    },
    global: {
      headers: {
        'Cache-Control': 'no-cache',
      },
    },
  }
);
